server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:3306/practice1?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100 # in query
    open-in-view: false
  output:
    ansi:
      enabled: always # vscode console color
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
logging:
  level:
    '[shop.wuchang.wuchangblog]': DEBUG
    '[org.hibernate.type]': TRACE

file:
  path: ./upload/