server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # DB직접 만들어야함
      default_batch_fetch_size: 100 # in query
    open-in-view: false
logging:
  level:
    '[shop.wuchang.wuchangblog]': INFO

file:
  path: ./upload/